import { useEffect, useState, useRef } from "react";
import { motion } from "framer-motion";
import { FileText, Send, Copy, Check, Upload, Download } from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { resumeApi } from "@/api/resume";
import type { Resume, GeneratedContent } from "@/types";
import jsPDF from "jspdf";
import { sanitizeForPdf } from "@/utils/sanitizePdf";

const contentTypes = [
  { value: "cover_letter" as const, label: "📝 Cover Letter", desc: "Professional cover letter for job application" },
  { value: "linkedin_summary" as const, label: "💼 LinkedIn Summary", desc: "Optimized LinkedIn About section" },
  { value: "professional_bio" as const, label: "👤 Professional Bio", desc: "Short professional biography" },
];

export function ContentGeneratorPage() {
  const [resumes, setResumes] = useState<Resume[]>([]);
  const [selectedResumeId, setSelectedResumeId] = useState("");
  const [jobDescription, setJobDescription] = useState("");
  const [selectedType, setSelectedType] = useState<"cover_letter" | "linkedin_summary" | "professional_bio">("cover_letter");
  const [result, setResult] = useState<GeneratedContent | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    resumeApi.getHistory()
      .then((data) => { if (cancelled) return; setResumes(data); if (data.length > 0) setSelectedResumeId(data[0].id); })
      .catch(() => {})
      .finally(() => { if (!cancelled) setIsLoading(false); });
    return () => { cancelled = true; };
  }, []);

  const handleGenerate = async () => {
    if (!selectedResumeId || !jobDescription.trim()) return;
    setIsGenerating(true);
    toast.loading("AI is writing...", { id: "content" });
    try {
      const res = await resumeApi.generateContent(selectedResumeId, jobDescription, selectedType);
      setResult(res);
      toast.success(`${res.type} generated!`, { id: "content" });
    } catch {
      toast.error("Generation failed", { id: "content" });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = () => {
    if (result) {
      navigator.clipboard.writeText(result.content);
      setCopied(true);
      toast.success("Copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadPDF = () => {
    if (!result) return;
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;

    // Header
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, pageWidth, 28, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(sanitizeForPdf(result.type), pageWidth / 2, 12, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by ResumeAI  -  ${new Date().toLocaleDateString()}`, pageWidth / 2, 22, { align: "center" });

    // Body — sanitize AI text for Latin-1 font compatibility
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(sanitizeForPdf(result.content), maxWidth);
    let y = 40;
    for (const line of lines) {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 6;
    }

    // Footer on all pages
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text(`Page ${i} of ${pages}`, pageWidth / 2, 290, { align: "center" });
    }

    const typeName = result.type.replace(/\s+/g, "_");
    doc.save(`Generated_${typeName}.pdf`);
    toast.success("PDF downloaded!");
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="h-8 w-64 animate-pulse rounded-lg bg-gray-200 dark:bg-gray-800" />
        <div className="grid gap-6 lg:grid-cols-2">
          <div className="h-[500px] animate-pulse rounded-2xl bg-gray-200 dark:bg-gray-800" />
          <div className="h-[500px] animate-pulse rounded-2xl bg-gray-200 dark:bg-gray-800" />
        </div>
      </div>
    );
  }

  if (resumes.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <FileText className="mb-4 h-16 w-16 text-gray-300 dark:text-gray-600" />
        <h2 className="mb-2 text-xl font-semibold text-gray-900 dark:text-white">No Resumes Found</h2>
        <p className="mb-6 text-gray-500">Upload a resume first</p>
        <Link to="/upload"><Button className="gap-2"><Upload className="h-4 w-4" /> Upload Resume</Button></Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">AI Content Generator</h1>
        <p className="text-gray-500 dark:text-slate-400">Generate cover letters, LinkedIn summaries & professional bios</p>
      </motion.div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Input */}
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Configuration</CardTitle>
              <CardDescription>Select resume, content type, and paste job description</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Resume</label>
                <select value={selectedResumeId} onChange={(e) => setSelectedResumeId(e.target.value)}
                  className="flex h-10 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm shadow-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100">
                  {resumes.map((r) => <option key={r.id} value={r.id}>{r.fileName} — {new Date(r.createdAt).toLocaleDateString()}</option>)}
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Content Type</label>
                <div className="grid gap-2">
                  {contentTypes.map((ct) => (
                    <button key={ct.value} onClick={() => { setSelectedType(ct.value); setResult(null); }}
                      className={`rounded-xl border p-3 text-left transition-all ${selectedType === ct.value
                        ? "border-brand-500 bg-brand-50 ring-2 ring-brand-500/20 dark:bg-brand-900/20"
                        : "border-gray-200 hover:border-gray-300 dark:border-gray-700"}`}>
                      <p className="text-sm font-semibold text-gray-900 dark:text-white">{ct.label}</p>
                      <p className="text-xs text-gray-500">{ct.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Job Description</label>
                <textarea value={jobDescription} onChange={(e) => setJobDescription(e.target.value)}
                  placeholder="Paste the job description here..."
                  rows={6}
                  className="w-full resize-none rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm shadow-sm placeholder:text-gray-400 focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100" />
              </div>

              <Button className="w-full gap-2 shadow-lg shadow-brand-500/25" onClick={handleGenerate}
                isLoading={isGenerating} disabled={!selectedResumeId || !jobDescription.trim()}>
                <Send className="h-4 w-4" /> Generate {contentTypes.find((c) => c.value === selectedType)?.label.replace(/^.+\s/, "")}
              </Button>
            </CardContent>
          </Card>
        </motion.div>

        {/* Output */}
        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}>
          <Card className="h-full">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>{result?.type || "Generated Content"}</CardTitle>
                {result && (
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="gap-1.5" onClick={handleDownloadPDF}>
                      <Download className="h-3 w-3" /> PDF
                    </Button>
                    <Button variant="outline" size="sm" className="gap-1.5" onClick={handleCopy}>
                      {copied ? <><Check className="h-3 w-3" /> Copied!</> : <><Copy className="h-3 w-3" /> Copy</>}
                    </Button>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {result ? (
                <motion.div ref={contentRef} initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  className="whitespace-pre-wrap rounded-xl border border-gray-200 bg-gray-50 p-5 text-sm leading-relaxed text-gray-800 dark:border-gray-700 dark:bg-gray-800/50 dark:text-gray-200">
                  {result.content}
                </motion.div>
              ) : (
                <div className="flex flex-col items-center justify-center py-16 text-center">
                  <span className="mb-3 text-5xl">✨</span>
                  <p className="text-sm text-gray-500">Select options and click Generate</p>
                </div>
              )}
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
